name: Publish Package to pypi

on: workflow_call

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ./dist/
      - name: Generate artifact attestation for sdist and wheel
        uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1.4.3
        with:
          subject-path: "dist/*"
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          attestations: true
